---
open_port: 8080
open_external_port: 80
secure_port: 8443
secure_external_port: 443
disable_http2: false
allow_un_escaped_chars: false
context_root: "/"
secure_key_alias: "unison-tls"
# force_to_secure: true
force_to_secure: false
activemq_dir: "/opt/openunison_ipa2/amq"
quartz_dir: "/opt/openunison_ipa2/quartz"
client_auth: none
allowed_client_names: []
ciphers:
- TLS_RSA_WITH_RC4_128_SHA
- TLS_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_AES_256_CBC_SHA
- TLS_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_AES_256_CBC_SHA256
path_to_deployment: "/opt/openunison_ipa2/work"
path_to_env_file: "/opt/openunison_ipa2/config/ou.env"
welcome_pages: ['index.html']
redirect_to_context_root: false
